services:
  wiremock:
    image: wiremock/wiremock:3.5.4
    container_name: wiremock-cfm
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--verbose"]

  wiremock-agendamento:
    image: wiremock/wiremock:3.5.4
    container_name: wiremock-agendamento
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: [ "--verbose"]
